### ISSUE TITLE
Can't build from both source and package

### ISSUE THREAD

**Issue by satanon2k1** [pymodsecurity/pymodsecurity#16]
I had this issue
'''
/root/pymodsecurity/src/action.cpp:2:40: fatal error: modsecurity/actions/action.h: No such file or directory
 #include <modsecurity/actions/action.h>
                                        ^
compilation terminated.
'''
I couldn't find modsecurity folder in src

**Comment by zimmerle** [comment]
@satanon2k1 It is very likely that you are trying to use the bindings with a version that is not yet supported.

**Comment by satanon2k1** [comment]
thanks
